### ISSUE TITLE
Just wondering outloud what is different here from Magic Areas?

### ISSUE THREAD

**Issue by Bodge-IT** [c-st/auto_areas#10]
It seems a shame Magic Areas couldn't be improved to add your requirements, given MA's wide feature set and Jan's appreciation for dev support.

**Comment by c-st** [comment]
Magic Areas is a fine extension no doubt about that!

However the wide feature set was exactly my problem: I didn't have a use for many of the new features that were added recently and many times the updates broke functionality for me (YMMV).

After this happened a few times to me, I decided to set up my own extension with a reduced feature set with a focus on testing these features well. 

Additionally, I was looking for a new pet project anyway...
