### ISSUE TITLE
Utilize scene.turn_on instead of turning on ALL lights when presence detected

### ISSUE THREAD

**Issue by rsnodgrass** [c-st/auto_areas#11]
Currently auto_areas assumes that ALL lights assigned to a room should be turned on (full) upon entry to the room. 

Ideally, a scene could be assigned for room entry which allows setting which lights to turn on, at what dimmable level, as well as other devices in a room that might be turned on (e.g. a fan, or climate setting). For leaving a room, a second scene would be needed to set the "away" settings for a room.

**Comment by rsnodgrass** [comment]
Three scenes are needed:

* Presence - scene activated when presence detected
* Sleep - scene activate when presence detected during sleep_mode
* Goodbye - scene activated when presence no longer detected

**Comment by c-st** [comment]
Hi @rsnodgrass. 

That's awesome! Thanks for the suggestion and immediately putting it into reality 😀. Yes, please go ahead and create a PR.

**Comment by c-st** [comment]
It's now possible to select a list of light entities to be excluded from light control.
