### ISSUE TITLE
All of my areas are "managed" even with no motion/occupancy/presence or light entities in them

### ISSUE THREAD

**Issue by danielbrunt57** [c-st/auto_areas#23]
## Version of the custom_component
v1.0.3

## Configuration
```yaml
auto_areas:
  bedroom:
    is_sleeping_area: true
```
## Describe the bug
"It checks each of your areas for relevant devices and starts managing them automatically. Additionally, it creates a few sensors and switches which allow you to adjust its behaviour as needed." - As it stands now, it manages all of my areas, even if there are no motion, occupancy or presence sensors in the area.

![image](https://user-images.githubusercontent.com/49846893/236581505-2056cccc-3410-4f0a-b084-679e16389f7e.png)

![image](https://user-images.githubusercontent.com/49846893/236581564-96a12431-3947-49e5-b1ea-d4a80c47ca6f.png)

## Debug log
N/A

**Comment by c-st** [comment]
This will not be an issue anymore once 2.0 is released.
