### ISSUE TITLE
Automatic lighting only at night?

### ISSUE THREAD

**Issue by danielbrunt57** [c-st/auto_areas#24]
**Is your feature request related to a problem? Please describe.**
I do not need automatic lighting in all areas.  
"Downstairs", "Garage" & "Bathroom" would be the _only_ areas needing 24x7 artificial lighting.

**Describe the solution you'd like**
Additional entitiies utilized to control automatic lighting. 
Eg.
1. binary_sensor, device class _light_.
2. sensor, device class _illuminance_.  This entity would require a threshold though to be specified which could get tricky so, a user created binary_sensor template with device_class _light_ would be the easiest and the integration need only check if that sensor is off.

**Describe alternatives you've considered**
Create automations to control the area_presence_lock entity, which is kludgy!

**Additional context**
None.

**Comment by c-st** [comment]
I agree, that's an issue. 

I'm planning on supporting this soon by allowing to:
- permanently disable auto-lights for certain areas
- use binary_sensor for turning of auto-lights 
 
Something similar to what you described in 2 could be realized based on #8. Only if the aggregated (avg/min/...) illuminance is below a certain threshold, automatic lights are enabled. But I'm not sure about this one yet as it's difficult to get right for every use case. I guess it would be more flexible to write an individual automation in which the binary_sensor mentioned above is set.

**Comment by c-st** [comment]
Hey @danielbrunt57. The new release introduces an aggregated illuminance sensor and allows to set an illuminance threshold. The lights are only turned on if the illuminance is going below the configured level. Happy to hear your feedback!
