### ISSUE TITLE
Join forces with magic_areas? 

### ISSUE THREAD

**Issue by tbrasser** [c-st/auto_areas#33]
### Checklist

- [X] I have filled out the template to the best of my ability.
- [X] This only contains 1 feature request (if you have multiple feature requests, open one feature request for each feature request).
- [X] This issue is not a duplicate feature request of [previous feature requests](https://github.com/ludeeus/integration_blueprint/issues?q=is%3Aissue+label%3A%22Feature+Request%22+).

### Is your feature request related to a problem? Please describe.

Hey, this looks great but also closely resembles magic_areas integration. Maybe you can combine forces?

https://github.com/jseidl/hass-magic_areas

### Describe the solution you'd like

Have 1 integration that is better than choosing between 2

### Describe alternatives you've considered

See above 

### Additional context

None needed

**Comment by c-st** [comment]
Hey!

I am aware of magic_areas. In fact, I was a user of this component for quite some time myself and I think it's a great project.

However, at some point I ran into issues and I had the feeling there were too many features which I was not using anyway. As a consequence I chose to build my own custom component - specifically suited for my use cases with as little code and complexity as possible.

Is there some feature you are missing from either auto_areas or magic_areas or what other benefits do you see in merging the projects?

**Comment by tbrasser** [comment]
Thanks for the info! Currently I'm pretty happy with magic_areas, just saw your project pop up on hacs and didn't know you started it specifically after having tried magic_areas.
