### ISSUE TITLE
Reset presence lock automatically

### ISSUE THREAD

**Issue by c-st** [c-st/auto_areas#6]
The motivation behind presence lock is to keep the light from going out if there is not much movement in an area. However, if forgotten It will keep the lights on indefinitely.

Discover how it could be reset automatically:
- based on time (after x minutes/hours)
- x hours after last presence was detected
- on the next day (sunrise)

Additionally it should be disabled if:
- sleep mode is turned on
- lights are turned off manually (?)

**Comment by rpatel3001** [comment]
Perhaps in addition or instead of this, there should be a delay when turning off binary_sensor.area_presence_{area_name} after all motion sensors clear.

**Comment by c-st** [comment]
> Perhaps in addition or instead of this, there should be a delay when turning off binary_sensor.area_presence_{area_name} after all motion sensors clear.

Yep. I have solved that by configuring the "occupancy timeout" of my motion sensors. Takes a bit of time to find a good value based on amount and placement of sensors, though. (Or if that's not possible in one's setup it should be possible to create a template sensor - but I haven't tried that yet).

I'd like to keep the logic and configuration options to a minimum. Preferably it would not be a time-based trigger but based on some user interaction (if possible).

**Comment by c-st** [comment]
IMO it's impossible to get a functionality like this right for everyone (or even most people). As a consequence I have decided not to implement this as a feature of Auto Areas. It is always possible to create an automation which would fit the user's use-case better.
