### ISSUE TITLE
Add general override

### ISSUE THREAD

**Issue by Stooovie** [c-st/auto_areas#9]
This system is very cool but until the user sets it up completely, there should be a general on/off switch that turns Auto Areas completely on and off so it doesn't interfere with existing automations.

**Comment by c-st** [comment]
Thanks. To understand this a bit better: what exactly happened when you set up the component and what is it you had to configure? Is it maybe something which could be solved with better documentation?

**Comment by Stooovie** [comment]
It immediatelly turned off lights in my room :) I understand that but a single switch that would turn the thing on and off would be nice.

**Comment by c-st** [comment]
Ah I see. Thanks for bringing it up, that is annoying for sure 😅. 
The current workaround would be to turn on the presence lock switch for this room. This way the lights would stay on.

**Comment by c-st** [comment]
I am considering to use config entries in the future so this custom component could completely be configured through UI. In this case the switch would not be necessary.

Closing this for now - feel free to open more issues should you run into any problems!
